### ISSUE TITLE
Left Aligned Text

### ISSUE THREAD

**Issue by mklauber** [kensanata/gridmapper#24]
Would it be possible to have a different starting character (perhaps the single quote) start text that is rendered left aligned from the target cell?  This could be useful for including a map key on the grid for use with numbered rooms.

**Comment by kensanata** [comment]
Sure. I just wonder: If you are writing a map key, would you not want more than just that?

- a white background that doesn't have grid lines
- a larger font
- what about line wrapping for long descriptions
- if lines wrap, what about aligning paragraphs

```
21 kitchen with
   magic cauldron
22 larder with dead
   cook
```

Perhaps a separate, multiline text field with a white background would be better?

**Comment by mklauber** [comment]
A white background would be nice, 
But honestly, I was planning on just manually line breaking i

**Comment by kensanata** [comment]
For the moment you can use `Z` to toggle background mode, but right now you only have grey or black to choose from... But my take away is that you'd be happy even as it is and if I added a white background mode, even better?

**Comment by mklauber** [comment]
Yep. And based on my glance at the code, it's pretty easy to add another
background variant?

**Comment by kensanata** [comment]
Yes, absolutely.

**Comment by kensanata** [comment]
White background mode is implemented in 771bc33, left aligned text is still missing.

**Comment by kensanata** [comment]
Hopefully #52592cd fixes this.

**Comment by kensanata** [comment]
And of course now I'm wondering whether we need right-aligned text for numbers that are supposed to be in that table, too...
