### ISSUE TITLE
edit in Inkscape

### ISSUE THREAD

**Issue by acodispo** [kensanata/gridmapper#29]
I'd like to edit in inkscape, but the resulting SVG seems to be missing something. Screenshot attached. Are certain fonts required, perhaps? I got this by following step 4 under How To Save. Thanks in advance!
![2017-04-01-155232_1920x1080_scrot](https://cloud.githubusercontent.com/assets/307073/24581955/69c0c3ce-16f3-11e7-81e5-d50c141ef89e.png)

**Comment by kensanata** [comment]
That might be the result of me moving attributes into CSS and Inkscape not taking these into account. Yikes! I'll definitely take a look.

**Comment by acodispo** [comment]
I appreciate it, thanks! And thanks for building this amazing tool in the first place. :-)

**Comment by kensanata** [comment]
The weird thing is that I can reproduce the effect, but I also know of a way to "fix" it: mark all, delete, undo. And suddenly it looks ok again. This makes me think that perhaps the problem lies elsewhere.

**Comment by acodispo** [comment]
> The weird thing is that I can reproduce the effect, but I also know of a way to "fix" it: mark all, delete, undo.

Well, that's interesting! Perhaps an Inkscape issue, then. At least now I can work around! Thanks!

**Comment by kensanata** [comment]
Maybe related: http://www.inkscapeforum.com/viewtopic.php?t=4000
I think at one point I removed the white fill of the tiles. I'll have to check and see why I removed it.

**Comment by kensanata** [comment]
Well, look at that. `git bisect` tells me 76ab766583f20dc08fd1fb9fdc467f839180e314 is the first bad commit.

**Comment by kensanata** [comment]
Minimal working example illustrating this behaviour:
```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <rect id="empty" width="10" height="10" stroke="black" stroke-width="1"/>
  </defs>
  <use x="10" y="10" xlink:href="#empty"/>
  <use x="20" y="10" class="red" xlink:href="#empty"/>
  <style><![CDATA[
  use.red { fill: #F6A17F; }
  use { fill: white; }
  ]]></style>
</svg>
```

**Comment by kensanata** [comment]
I reported this as an [Inkscape bug](https://bugs.launchpad.net/inkscape/+bug/1680778).
