### ISSUE TITLE
Grey background to grey grid

### ISSUE THREAD

**Issue by cb-nz** [kensanata/gridmapper#30]
Wonder if it is possible to turn the solid grey (unmapped) background into a grey grid and toggle between.

Reason you may want to do this is if you have a partially explored dungeon and you map on paper in game having the explored area surrounded by a printed grid to map further makes life easier, particularly as you have  your previously explored areas on the paper you can catch mapping errors

This is similar to the previous blue grid/black walls request - but not entirely the same

Thanks

**Comment by kensanata** [comment]
Hm, I'll think about it. It's harder than simply changing the color unless I manage to create a SVG pattern that exactly matches the empty floor tiles. It might work, though.

**Comment by cb-nz** [comment]
The idea came because I use Anamap - which you refer to - but it has some flaws.  The issue I find is that the map size is not easily scaleable but I do like the default light background .... if only the grid printed out a bit better.  I also wondered if you could transfer maps between gridmapper and Anamap (which saves a a .json file) but figured converting the information between the two, even if only rooms and not objects, but might be tricky even though both seem to use some form of text notation for referencing rooms.

The other issue I ran across with gridmapper is that you can extend the page size down and right but not left or up which may be because top left is 0,0.  I assume the way to move a map that needs to extend in those directions is export as text, add spaces, and import but it never seems to work accurately.

Really do like the tool by the way.

**Comment by kensanata** [comment]
Hopefully cut and paste "solved" the problem of not being able to easily add rows and columns to the left and top.

**Comment by kensanata** [comment]
![screen shot 2017-04-29 at 12 27 56](https://cloud.githubusercontent.com/assets/1145712/25554807/6056d6e4-2cd7-11e7-8b90-b98b99f20296.png)

**Comment by kensanata** [comment]
What do you think?

**Comment by kensanata** [comment]
See 833efa0.

**Comment by kensanata** [comment]
I guess the alternative is worse: just fill the dungeon level below with floor tiles. :)

![screen shot 2017-04-29 at 12 52 14](https://cloud.githubusercontent.com/assets/1145712/25554925/bc8c0a12-2cda-11e7-98de-f38456d498b6.png)

**Comment by kensanata** [comment]
Tested locally on Chrome, Firefox and Safari. Going to deploy this. Feel free to add notes on UI preferences (lighter, darker, contrast, that kind of thing).

**Comment by cb-nz** [comment]
Looks excellent - thanks!

**Comment by cb-nz** [comment]
That was the quick fix I used - then our GM presented us with stairs going
down! :-)
