### ISSUE TITLE
"crosshair" column support

### ISSUE THREAD

**Issue by timothystone** [kensanata/gridmapper#34]
A version of the column type that has what I'll call, clockwise, NW, SW, SE, and NE column "quarters" for creating columns on the grid crosshair.

```
o--+     +--o     +--+     +--+
|  |     |  |     |  |     |  |
+--+     +--+     o--+     +--o
```

allowing you to create rooms like

```
+--+--+
|  |  |
+--o--+
|  |  |
+--+--+
```

**Comment by kensanata** [comment]
I hope that works for you. :)
This was also in #17.
