### ISSUE TITLE
Interpret period as next instruction

### ISSUE THREAD

**Issue by Pajamaman** [kensanata/gridmapper#5]
Often, I want to test what a particular set of instructions does. Say I have the following code, which was exported from the editor:

    w.d.w8f

In order to reproduce this in the editor, I can:

1. Type "w", move the cursor, move it back, type "d", move the cursor, move it back, type "w8f".
2. Type that code into the text import field and import it.

The first method is kind of a pain due to the amount of keystrokes/mouse movements. The second is also a pain because there's no way to backspace in the text import field.

So it would be a nice if I could just type the code directly in to the editor. i.e., instead of typing "w", moving the cursor, moving it back, etc., just typing "w.d.w8f" and seeing the results right away.

**Comment by kensanata** [comment]
I'm not sure I understand the problem. Did you try simply typing ```wdw8f```? The result looks the same as if I had pasted ```w.d.w8f``` into the text area and imported it. In fact, the dot by itself is a no-op, so you can type ```w.d.w8f``` and get the same result. Why is it necessary to move the cursor and move it back again whenever there is a dot?

**Comment by Pajamaman** [comment]
Ah, sorry, that was a bad example. Try the following:

    w.w.w.w

**Comment by kensanata** [comment]
Actually, there is a suboptimal alternative: waiting 2s. But I see the point, now. SHA: 926db4c lets the user type ```.``` and get the same effect as when importing ```.``` from the text area. Does that solve the problem?

**Comment by Pajamaman** [comment]
Amazing. How do I test it?

**Comment by kensanata** [comment]
I'm not sure how you run it. I installed it on campaignwiki.org – if you installed it locally, you'll have to download a new copy, of course.

**Comment by kensanata** [comment]
As for backspace in the text field – it works for me (Firefox on a Mac). What are you using? If you want to investigate, set a breakpoint in the keyPressed function and look at what kind of event you got. Also, consider opening a separate issue. Also, make sure you test this without any add-ons interfering! :)
